/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo */

#ifndef _Included_jnidemo
#define _Included_jnidemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemo
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnidemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
